src/apps/cards/urls.py
from django.urls import path, include
from .views import (
    CardListView, CardReminderCreateView, CardDetailView, CardReminderUpdateView, CardDeleteView, GoalEditView,
    GoalCreateView, GoalDeleteView
)


app_name = 'cards'

goal_patterns = [
    path('', GoalCreateView.as_view(), name='goal-new'),
    path('<int:goal_pk>/', GoalEditView.as_view(), name='goal-detail'),
    # path('<int:goal_pk>/delete/', delete_goal, name='goal-delete'),
    path('<int:goal_pk>/delete/', GoalDeleteView.as_view(), name='goal-delete'),
]

urlpatterns = [
    path('', CardListView.as_view(), name='list'),
    path('new/', CardReminderCreateView.as_view(), name='new'),
    path('<int:card_pk>/', CardDetailView.as_view(), name='detail'),
    path('<int:card_pk>/update/', CardReminderUpdateView.as_view(), name='update'),
    path('<int:card_pk>/delete/', CardDeleteView.as_view(), name='delete'),
    path('<int:card_pk>/goal/', include(goal_patterns)),
    # path('<int:card_pk>/goal/<int:goal_pk>/', GoalEditView.as_view(), name='goal-detail'),
    # path('<int:card_pk>/goal/<int:goal_pk>/delete/', GoalDeleteView.as_view(), name='goal-delete'),
    # path('<int:card_pk>/goal/<int:goal_pk>', GoalDeleteView.as_view(), name='goal-delete'), ### ???
    # path('<int:card_pk>/update/', CardUpdateView.as_view(), name='update'),
    # path('new/', cardCreateView.as_view(), name='new'),
]

src/apps/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    WelcomePageView, HomePageView, ChangePasswordView, PasswordChangeDoneView, PasswordResetCustomView,
    PasswordResetDoneCustomView, PasswordResetConfirmCustomView, PasswordResetCompleteCustomView,
                    )

app_name = 'common'

urlpatterns = [

    # Common URL`s
    path('', WelcomePageView.as_view(), name='welcome-page'),
    path('home/', HomePageView.as_view(), name='home-page'),


    # Auth URL`s
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login-page'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout-page'),


    # Password change & reset URL`s
    path('user/change_password/', ChangePasswordView.as_view(), name='password-change-page'),
    path('user/change_password/done', PasswordChangeDoneView.as_view(), name='password-change-done-page'),

    path('password_reset/', PasswordResetCustomView.as_view(), name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneCustomView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmCustomView.as_view(), name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteCustomView.as_view(),
         name='password_reset_complete'),
]

src/apps/users/urls.py
from django.urls import path

from .views import UserRegisterView, UserProfileView, UserDeleteView

app_name = 'users'

urlpatterns = [

    # User profile URL`s
    path('register/', UserRegisterView.as_view(), name='register-page'),
    path('<int:user_pk>/profile/', UserProfileView.as_view(), name='profile-page'),
    path('<int:user_pk>/profile/delete/', UserDeleteView.as_view(), name='delete-page'),

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.common.urls', namespace='common')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('cards/', include('apps.cards.urls', namespace='cards')),
    # path('api/', include('apps.api.urls', namespace='api')),
]

src/apps/common/models.py
from django.db import models

# Create your models here.

src/apps/common/views.py
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth import views as auth_views
from django.utils.translation import gettext_lazy as _
from apps.users.models import CardUser


# Homepage View`s
class HomePageView(LoginRequiredMixin, generic.TemplateView):

    template_name = 'home.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)
        return redirect(to=reverse('common:welcome-page'))


# Welcome page view
class WelcomePageView(generic.TemplateView):
    template_name = 'welcome.html'


# Password Change View`s
class ChangePasswordView(auth_views.PasswordChangeView):
    model = CardUser
    form_class = PasswordChangeForm
    template_name = 'registration/password/password_change.html'
    success_url = reverse_lazy('common:password-change-done-page')


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = 'registration/password/password_changed_done.html'
    title = _('Password change successful')


# Password Reset View`s
class PasswordResetCustomView(auth_views.PasswordResetView):
    success_url = reverse_lazy('common:password_reset_done')
    email_template_name = 'registration/password/password_reset_email.html'
    subject_template_name = 'registration/password/password_reset_subject.txt'
    template_name = 'registration/password/password_reset_form.html'


class PasswordResetDoneCustomView(auth_views.PasswordResetDoneView):
    template_name = 'registration/password/password_reset_done.html'
    pass


class PasswordResetCompleteCustomView(auth_views.PasswordResetCompleteView):
    template_name = 'registration/password/password_reset_complete.html'
    pass


class PasswordResetConfirmCustomView(auth_views.PasswordResetConfirmView):
    form_class = SetPasswordForm
    success_url = reverse_lazy('common:password_reset_complete')
    template_name = 'registration/password/password_reset_confirm.html'

src/apps/common/templates/Base2.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
    <style type="text/css">
        .sidenav {
            height:100%;
            width:160px;
            position:fixed;
            z-index:1;
            top:0;
            left:0;
            background-color:#483D8B;
            overflow-x:hidden;
            padding-top:20px;
        }

        .sidenav a {
            padding:6px 8px 6px 16px;
            text-decoration:none;
            font-size:25px;
            color:#FF8C00;
            display:block;
        }

        .sidenav a:hover{
            color:#F0F8FF
        }

        .main {
            margin-left:160px;
            padding: 10px;
        }

        footer {
<!--            clear: both;-->
            bottom:0;
            position: absolute;
            height: 200px;
            width:100%;
            margin-top: -200px;
        }
    </style>

    <meta charset="UTF-8">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="sidenav">
        {% block sidenav %}
        {% if request.user.is_authenticated %}
                <a href="{% url 'common:home-page' %}">Home</a>
                <a href="{% url 'common:logout-page' %}">Logout</a>
                <a href="{% url 'cards:list' %}">My cards</a>
                <a href="{% url 'users:profile-page' user.id %}">Profile</a>
        {% else %}
                <a href="{% url 'common:home-page' %}">Home</a>
                <a href="{% url 'common:login-page' %}">Login</a>
                <a href="{% url 'users:register-page' %}">Register</a>
        {% endif %}
        {% endblock %}
    </div>

    <div id="content" name="content" class="main">
        {% block main_container %}
        {% endblock %}
    </div>

</body>

src/apps/common/templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- Created by CodingLab |www.youtube.com/CodingLabYT-->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
<!-- CSS Style -->
    <link rel="stylesheet" href="{% static 'common/css/style.css' %}">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="sidebar">
    <div class="logo-details">
      <i class='bx bx-analyse icon'></i>
        <div class="logo_name">
            Self Tracker
        </div>
        <i class='bx bx-menu' id="btn" ></i>
    </div>
    <ul class="nav-list">
        {% if request.user.is_authenticated %}
      <li>
          <i class='bx bx-search' ></i>
         <input type="text" placeholder="Search...">
         <span class="tooltip">Search</span>
      </li>
      <li>
        <a href="{% url 'cards:list' %}">
          <i class='bx bx-grid-alt'></i>
          <span class="links_name">My cards</span>
        </a>
         <span class="tooltip">My cards</span>
      </li>
      <li>
       <a href="{% url 'users:profile-page' user.id %}">
         <i class='bx bx-user' ></i>
         <span class="links_name">Profile</span>
       </a>
       <span class="tooltip">Profile</span>
     </li>
     <li>
       <a href="#">
         <i class='bx bx-chat' ></i>
         <span class="links_name">Messages</span>
       </a>
       <span class="tooltip">Messages</span>
     </li>
     <li>
       <a href="#">
         <i class='bx bx-pie-chart-alt-2' ></i>
         <span class="links_name">Analytics</span>
       </a>
       <span class="tooltip">Analytics</span>
     </li>
     <li>
       <a href="#">
         <i class='bx bx-folder' ></i>
         <span class="links_name">File Manager</span>
       </a>
       <span class="tooltip">Files</span>
     </li>
     <li>
       <a href="#">
         <i class='bx bx-cart-alt' ></i>
         <span class="links_name">Order</span>
       </a>
       <span class="tooltip">Order</span>
     </li>
     <li>
       <a href="#">
         <i class='bx bx-heart' ></i>
         <span class="links_name">Saved</span>
       </a>
       <span class="tooltip">Saved</span>
     </li>
     <li>
       <a href="#">
         <i class='bx bx-cog' ></i>
         <span class="links_name">Setting</span>
       </a>
       <span class="tooltip">Setting</span>
     </li>
     <li class="profile">
         <div class="profile-details">
           <img src="profile.jpg" alt="profileImg">
           <div class="name_job">
             <div class="name">Prem Shahi</div>
             <div class="job">Web designer</div>
           </div>
         </div>
         <a href="{% url 'common:logout-page' %}">
            <i class='bx bx-log-out' id="log_out" ></i>
             <span class="links_name">Logout</span>
         </a>
     </li>
        {% else %}
     <li class="log_in">
         <a href="{% url 'common:login-page' %}">
            <i class='bx bxs-log-in' id="log_in"></i>
             <span class="links_name">Login</span>
         </a>
         <span class="tooltip">Login</span>
     </li>
     <li class="register">
         <a href="{% url 'users:register-page' %}">
             <i class='bx bx-link' id="register"></i>
             <span class="links_name">Registration</span>
         </a>
         <span class="tooltip">Registration</span>
     </li>
     <li class="unknown-profile">
         <div class="unknown-profile-details">
           <img src="{% static 'users/images/unknown_user_photo_v2.png' %}" alt="UnknownProfileImg">
           <div class="name_job">
             <div class="name">Unknown user</div>
           </div>
         </div>
     </li>
        {% endif %}
    </ul>
  </div>
  <section class="home-section">
      {% block main_container %}
        {% endblock %}
  </section>
  <script src="{% static 'common/js/sidebars.js' %}"></script>
</body>
</html>

src/apps/common/templates/base_old_3.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %}{% endblock %}</title>


    <!-- Bootstrap core CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- Favicons -->
<meta name="theme-color" content="#7952b3">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .addition {
        margin-left:160px;
        padding: 10px;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">
  </head>
  <body>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="home" viewBox="0 0 16 16">
    <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"/>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
    <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
  </symbol>
  <symbol id="calendar3" viewBox="0 0 16 16">
    <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
    <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
  </symbol>
  <symbol id="to-register" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
    <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
  </symbol>
  <symbol id="to-login" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
    <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
  </symbol>
</svg>

<main>
<!--  <h1 class="visually-hidden">Sidebars examples</h1>-->
  <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    {% if request.user.is_authenticated %}
      <div class="dropdown">
          <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="64" height="64" class="rounded-circle me-2">
            <strong>mdo</strong>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="{% url 'users:profile-page' user.id %}">Profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'common:logout-page' %}">Log out</a></li>
          </ul>
      </div>
    <hr>
    {% endif %}
    <ul class="nav nav-pills flex-column mb-auto" data-tag>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a href="{% url 'common:home-page' %}" class="nav-link text-white" aria-current="page" >
          <svg class="bi me-2" width="48" height="48"><use xlink:href="#home"/></svg>
          Home
        </a>
      </li>
      <li>
        <a href="{% url 'cards:list' %}" class="nav-link text-white">
          <svg class="bi me-2" width="48" height="48"><use xlink:href="#grid"/></svg>
          My Cards
        </a>
      </li>
        <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="48" height="48"><use xlink:href="#speedometer2"/></svg>
          Dashboard
        </a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'users:register-page' %}" class="nav-link text-white">
          <svg class="bi bi-box-arrow-up-right" width="48" height="48"><use xlink:href="#to-register"/></svg>
          Register
        </a>
      </li>
      <li>
        <a href="{% url 'common:login-page' %}" class="nav-link text-white">
          <svg class="bi bi-box-arrow-in-right" width="48" height="48"><use xlink:href="#to-login"/></svg>
          Login
        </a>
      </li>
      {% endif %}
    </ul>
    <hr>
  </div>

</main>
  <div class="b-example-divider"></div>
      <div id="content" name="content" class="addition">
        {% block main_container %}
        {% endblock %}
    </div>

    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
      <script src="{% static 'js/sidebars.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

src/apps/common/templates/home.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block main_container %}
<a>You are welcome at your home page</a>
{% endblock %}

src/apps/common/templates/welcome.html
{% extends 'base.html' %}

{% block title %}Welcome page{% endblock %}

{% block main_container %}
WELCOME AT NEW SELF_TRACKER app
{% endblock %}