src/apps/cards/urls.py
from django.urls import path, include
from .views import (
    CardListView, CardReminderCreateView, CardDetailView, CardReminderUpdateView, CardDeleteView, GoalEditView,
    GoalCreateView, GoalDeleteView
)


app_name = 'cards'

goal_patterns = [
    path('', GoalCreateView.as_view(), name='goal-new'),
    path('<int:goal_pk>/', GoalEditView.as_view(), name='goal-detail'),
    # path('<int:goal_pk>/delete/', delete_goal, name='goal-delete'),
    path('<int:goal_pk>/delete/', GoalDeleteView.as_view(), name='goal-delete'),
]

urlpatterns = [
    path('', CardListView.as_view(), name='list'),
    path('new/', CardReminderCreateView.as_view(), name='new'),
    path('<int:card_pk>/', CardDetailView.as_view(), name='detail'),
    path('<int:card_pk>/update/', CardReminderUpdateView.as_view(), name='update'),
    path('<int:card_pk>/delete/', CardDeleteView.as_view(), name='delete'),
    path('<int:card_pk>/goal/', include(goal_patterns)),
    # path('<int:card_pk>/goal/<int:goal_pk>/', GoalEditView.as_view(), name='goal-detail'),
    # path('<int:card_pk>/goal/<int:goal_pk>/delete/', GoalDeleteView.as_view(), name='goal-delete'),
    # path('<int:card_pk>/goal/<int:goal_pk>', GoalDeleteView.as_view(), name='goal-delete'), ### ???
    # path('<int:card_pk>/update/', CardUpdateView.as_view(), name='update'),
    # path('new/', cardCreateView.as_view(), name='new'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.common.urls', namespace='common')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('cards/', include('apps.cards.urls', namespace='cards')),
    # path('api/', include('apps.api.urls', namespace='api')),
]

src/apps/cards/models.py
from django.db import models
from config import settings
from django.utils import timezone


# Create your models here.
class Card(models.Model):

    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='cards',
    )

    title = models.CharField(
        max_length=100,
        blank=False,
    )

    description = models.TextField(
        max_length=255,
    )

    created_at = models.DateField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        verbose_name = 'Card'
        verbose_name_plural = 'Cards'

    def __str__(self):
        return f'Card name: {self.title}. Username: {self.user}'

    def get_absolute_url(self):
        return f'/cards/{self.id}/'


# Reminders
class ReminderQuerySet(models.QuerySet):

    def is_active(self):
        return self.filter(is_active=True)


class Reminder(models.Model):
    card = models.OneToOneField(
        to=Card,
        on_delete=models.CASCADE,
        related_name='reminders'
    )

    is_active = models.BooleanField(
        default=False,
        null=True,
        blank=True,
    )

    remind_time = models.TimeField(
        default='21:00',
        null=True,
        blank=True,
    )

    remind_date = models.DateField(
        auto_now_add=True,
    )

    comment = models.TextField(
        max_length=255,
        blank=True,
        default='Add comment here'
    )

    created_at = models.DateTimeField(
        auto_now=True,
    )

    objects = ReminderQuerySet.as_manager()

    class Meta:
        verbose_name = "Reminder"
        verbose_name_plural = "Reminders"

    def __str__(self):
        return f'{self.comment}: status:{self.is_active} at {self.remind_time}'


# Goals
class Goal(models.Model):

    card = models.ForeignKey(
        to=Card,
        on_delete=models.CASCADE,
        related_name='goals',
    )

    title = models.CharField(
        max_length=50,
        blank=False,
    )

    description = models.TextField(
        max_length=255,
    )

    class Meta:
        verbose_name = "Goal"
        verbose_name_plural = "Goals"

    def get_absolute_url(self):
        return f'/cards/{self.card.id}/goal/{self.id}/'

    def get_delete_url(self):
        return f'/cards/{self.card.id}/goal/{self.id}/delete/'

    def __str__(self):
        return f'{self.title}: description:{self.description}'


class Rating(models.Model):

    goal = models.ForeignKey(
        to=Goal,
        on_delete=models.CASCADE,
        related_name='ratings',
    )

    value = models.IntegerField(
        default=0,
        blank=True,
    )

    created_at = models.DateField(
        auto_now_add=True,
    )

src/apps/cards/forms.py
from django import forms
from .models import Card, Goal, Reminder
from django.utils import timezone


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ('title', 'description', )


class ReminderForm(forms.ModelForm):

    class Meta:
        model = Reminder
        fields = ('comment', 'is_active', 'remind_time',)


class GoalForm(forms.ModelForm):

    class Meta:
        model = Goal
        fields = ('title', 'description', )


class RatingForm(forms.Form):

    value = forms.IntegerField(max_value=10, min_value=0)

src/apps/cards/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic.edit import ProcessFormView, BaseFormView
from django.utils import timezone

from .forms import CardForm, ReminderForm, GoalForm, RatingForm
from .models import Card, Goal, Reminder, Rating
from config import settings


# Create your views here.
class CardListView(LoginRequiredMixin, generic.ListView):
    model = Card
    context_object_name = 'cards'
    template_name = 'cards/list.html'
    login_url = settings.LOGIN_REDIRECT_URL

    def get_queryset(self):
        return Card.objects.filter(user=self.request.user)


class CardDetailView(LoginRequiredMixin, generic.DetailView):
    model = Card
    pk_url_kwarg = 'card_pk'
    template_name = 'cards/detail.html'
    context_object_name = 'card'

    def dispatch(self, request, *args, **kwargs):
        card = self.get_object()
        if request.user.is_authenticated and card.user.id == request.user.id:
            return super().dispatch(request, *args, **kwargs)
        return redirect(to=reverse_lazy('common:home-page'))


class CardDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Card
    pk_url_kwarg = 'card_pk'
    template_name = 'cards/delete.html'
    success_url = reverse_lazy('cards:list')

    def dispatch(self, request, *args, **kwargs):
        card = self.get_object()
        if request.user.is_authenticated and card.user.id == request.user.id:
            return super().dispatch(request, *args, **kwargs)
        return redirect(to=reverse_lazy('common:home-page'))


# REMINDER`s VIEWS
class CardReminderCreateView(LoginRequiredMixin, ProcessFormView):
    template_name = 'cards/new.html'
    card_form = CardForm
    reminder_form = ReminderForm
    title = 'Create page'

    def get(self, request, *args, **kwargs):
        context = {
            'card_form': self.card_form,
            'reminder_form': self.reminder_form,
            'title': self.title,
        }
        return render(request, self.template_name, context or {})

    def post(self, request, *args, **kwargs):

        card_form = self.card_form(request.POST)
        reminder_form = self.reminder_form(request.POST)
        context = {
            'card_form': self.card_form,
            'reminder_form': self.reminder_form,
        }

        if card_form.is_valid() and reminder_form.is_valid():

            # Card part
            card_form.instance.user = request.user
            card_form.save()

            # Reminder part
            reminder_form.instance.card = card_form.instance
            reminder_form.save()

            return HttpResponseRedirect(reverse('cards:list'))

        return render(request, self.template_name, context or {})


class CardReminderUpdateView(LoginRequiredMixin, BaseFormView):
    pk_url_kwarg = 'card_pk'
    template_name = 'cards/update.html'
    success_url = reverse_lazy('cards:list')

    def get(self, request, *args, **kwargs):

        # Card part
        card_pk = self.kwargs.get('card_pk')
        card = get_object_or_404(Card, pk=card_pk)
        card_form = CardForm(instance=card)

        # Reminder part
        reminder = get_object_or_404(Reminder, pk=card.reminders.id)
        reminder_form = ReminderForm(instance=reminder)
        context = {
            'card_form': card_form,
            'reminder_form': reminder_form,
        }
        return render(request, self.template_name, context or {})

    def post(self, request, *args, **kwargs):

        # Card part
        card_pk = self.kwargs.get('card_pk')
        card = get_object_or_404(Card, pk=card_pk)
        card_form = CardForm(instance=card)

        # Reminder part
        reminder = get_object_or_404(Reminder, pk=card.reminders.id)
        reminder_form = ReminderForm(instance=reminder)

        context = {
            'card_form': card_form,
            'reminder_form': reminder_form,
        }

        if card_form.is_valid and reminder_form.is_valid:

            # Card part
            card.title = self.request.POST.get('title')
            card.description = self.request.POST.get('description')
            # card.evaluation = self.request.POST.get('evaluation')

            # Reminder part
            is_active = False
            if self.request.POST.get('is_active') == 'true':
                is_active = True

            reminder.comment = self.request.POST.get('comment')
            reminder.remind_time = self.request.POST.get('remind_time')
            reminder.is_active = is_active

            if card.user == request.user:
                card.save()
                reminder.save()
                return HttpResponseRedirect(reverse('cards:list'))

        return render(request, self.template_name, context or {})

    def dispatch(self, request, *args, **kwargs):
        card_pk = self.kwargs.get('card_pk')
        card = get_object_or_404(Card, pk=card_pk)
        if request.user.is_authenticated and card.user.id == request.user.id:
            return super().dispatch(request, *args, **kwargs)
        return redirect(to=reverse_lazy('common:home-page'))


# Goal`s Views
class GoalCreateView(LoginRequiredMixin, generic.CreateView):
    model = Goal
    template_name = 'goals/new.html'
    fields = ('title', 'description', )
    context_object_name = 'goal'

    login_url = settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.card = self.get_card()
        obj.save()
        return HttpResponseRedirect(obj.card.get_absolute_url())

    def get_card(self):
        return get_object_or_404(Card, id=self.kwargs.get('card_pk'))


class GoalEditView(LoginRequiredMixin, generic.UpdateView):

    model = Goal
    template_name = 'goals/detail.html'
    form_class = GoalForm
    pk_url_kwarg = 'goal_pk'
    context_object_name = 'goal'

    def get_success_url(self):
        return self.object.card.get_absolute_url()

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)
        return redirect(to=reverse_lazy('common:home-page'))


class GoalDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Goal
    pk_url_kwarg = 'goal_pk'
    template_name = 'goals/delete.html'

    def get_success_url(self):
        return self.object.card.get_absolute_url()


# REMINDER`s VIEWS
class CardReminderCreateView(LoginRequiredMixin, ProcessFormView):
    template_name = 'cards/new.html'
    card_form = CardForm
    reminder_form = ReminderForm
    title = 'Create page'

    def get(self, request, *args, **kwargs):
        context = {
            'card_form': self.card_form,
            'reminder_form': self.reminder_form,
            'title': self.title,
        }
        return render(request, self.template_name, context or {})

    def post(self, request, *args, **kwargs):

        card_form = self.card_form(request.POST)
        reminder_form = self.reminder_form(request.POST)
        context = {
            'card_form': self.card_form,
            'reminder_form': self.reminder_form,
        }

        if card_form.is_valid() and reminder_form.is_valid():

            # Card part
            card_form.instance.user = request.user
            card_form.save()

            # Reminder part
            reminder_form.instance.card = card_form.instance
            reminder_form.save()

            return HttpResponseRedirect(reverse('cards:list'))

        return render(request, self.template_name, context or {})

src/apps/cards/templates/cards/delete.html
{% extends 'base.html' %}
{% block title %}
Card delete
{% endblock %}

{% load crispy_forms_tags %}

{% block main_container %}
<form method="POST">
  {% csrf_token %}
  <p>Are You sure want to delete this Card?</p>
  <input type="submit" value="Confirm">
</form>
{% endblock %}

src/apps/cards/templates/cards/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Card{{ card.id }}{% endblock %}

{% block main_container %}
    <h1>My Card: {{ card.title }}</h1>
    <br>
    My goals:
    <div>
        {% for goal in card.goals.all %}
        <a href="{{ goal.get_absolute_url }}">{{ goal.title }}</a>
        <p>{{ goal.description|truncatewords:5 }}</p>
        {% endfor %}
        <br>
        <form action="{% url 'cards:goal-new' card.id %}">
            <input type="submit" value="Add new goal">
        </form>
    </div>
        <br>
    <form>
        <button type="submit" formaction="{% url 'cards:update' card.id %}">Update</button>
    </form>
        <br>
    <form>
        <button type="submit" formaction="delete/">Delete</button>
    </form>
{% endblock %}

src/apps/cards/templates/cards/list.html
{% extends 'base.html' %}
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %} Card List {% endblock %}</title>
<!-- CSS Style -->
<link rel="stylesheet" href="{% static 'cards/css/list_style.css' %}">
    <!-- Boxicons CDN Link -->
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>

{% block main_container %}
<link rel="stylesheet" href="{% static 'cards/css/list_style.css' %}">
<div class="flex-container">
  {% for card in cards %}
        <div class="card-container">
            <div class="card-top">
                <div class="card-title">
                    <h3>{{ card.title }}</h3>
                </div>
            </div>
            <div class="card-center">
                <div class="card-description">
                    <p>{{ card.description|truncatewords:5 }}</p>
                </div>
            </div>
            <div class="card-bottom">
                <div class="card-detail">
                    <a href="{{ card.get_absolute_url }}">
                        <i class='bx bxs-edit' id='detail-image'></i>
                    </a>
                </div>
                <div class="card-rating">
                    <a>Daily score:
                        <output>5</output>
                    </a>    
                </div>
            </div>
        </div>
    {% endfor %}
    <a href="{% url 'cards:new' %}">
        <div class="card-container">
            <div class="card-center">
                <div class="card-image-plus">
                    <i class='bx bx-plus' id="plus-image"></i>
                </div>
            </div>
        </div>
    </a>
</div>

{% endblock %}

src/apps/cards/templates/cards/list_old.html
{% extends 'base.html' %}
{% block title %}
card List
{% endblock %}

{% block main_container %}
    <h1>Card list</h1>
    <a>User: {{ request.user }}</a>
    {% for card in cards %}
    <p>
        <a href="{{ card.get_absolute_url }}" >{{ card.title }}</a>
        <a>{{ card.description|truncatewords:5 }}</a>
        <a>{{ card.reminders.remind_time }}</a>
        <a>{{ card.reminders.is_active }}</a>
    </p>
    <br>
    {% endfor %}
    <form>
        <h2>{{ cards.get_create_url }}</h2>
        <button type="submit" formaction="{% url 'cards:new' %}">Add new card</button>
    </form>
{% endblock %}

src/apps/cards/templates/cards/new.html
{% extends 'base.html' %}
{% block title %}
{{ title }}
{% endblock %}

{% load crispy_forms_tags %}

{% block main_container %}
    <form action="." method="POST">
        {% csrf_token %}
        {{ card_form|crispy }}
        {{ reminder_form|crispy }}
        <button type="submit">Confirm</button>
    </form>
{% endblock %}

src/apps/cards/templates/cards/new_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/apps/cards/templates/cards/update.html
{% extends 'base.html' %}
{% block title %}
Update
{% endblock %}

{% load crispy_forms_tags %}
{% include reminders.reminder.html %}
{% block main_container %}
<form method="POST">
        {% csrf_token %}
        {{ card_form|crispy }}
        {{ reminder_form|crispy }}
        {% block reminder %}{% endblock %}
        <br>
        <input type="submit" value="Confirm changes">
        <br>
        <button type="reset">Discard</button>
        <br>
        </button>
</form>
{% endblock %}